### ISSUE TITLE
模组不再适用于 JDK 21 或更高版本

### ISSUE THREAD

**Issue by SanQianQVQ** [Tigercrl/NonUpdateReloaded#7]
nonupdate_reloaded 模组在初始化过程中调用了已被弃用的 Security Manager，而这在 Java 的新版本（如 Java 17 及更高版本）中不再被允许。

**Comment by Tigercrl** [comment]
添加JVM参数 -Djava.security.manager=allow 有空写自动启用Security Manager的

**Comment by LTCatt** [comment]
添加 `-Djava.security.manager=allow` 会导致其他 Mod 崩溃，所以还是用不了这个 Mod……

<details><summary>Details</summary>
<p>

```
[073月2026 01:11:01.846] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font 'minecraft:alt' in pack: 'vanilla'
[073月2026 01:11:01.849] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font bundle: 'minecraft:font/alt.json', font set: [minecraft:include/space,minecraft:font/ascii_sga.png]
[073月2026 01:11:01.851] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font 'supplementaries:antiquable' in pack: 'mod_resources'
[073月2026 01:11:01.851] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font bundle: 'supplementaries:font/antiquable.json', font set: [minecraft:include/space,supplementaries:include/antiquable,modernui:internal-default]
[073月2026 01:11:01.875] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: setContextClassLoader
	Index: 2
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda/0x0000000080b2d338@46a636e2
		2: net.minecraftforge.eventbus.EventBus$$Lambda/0x0000000080b2d338@6dc145c5
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:231)
	at LAYER SERVICE/org.sinytra.connector@1.0.0-beta.46+1.20.1/org.sinytra.connector.service.hacks.ConnectorForkJoinThreadFactory.newThread(ConnectorForkJoinThreadFactory.java:25)
	at java.base/java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1574)
	at java.base/java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1712)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.push(ForkJoinPool.java:1156)
	at java.base/java.util.concurrent.ForkJoinPool.poolSubmit(ForkJoinPool.java:2370)
	at java.base/java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2847)
	at java.base/java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1818)
	at java.base/java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:2018)
	at TRANSFORMER/modernui@3.12.0.1/icyllis.modernui.mc.ModernUIClient.loadFonts(ModernUIClient.java:259)
	at TRANSFORMER/modernui@3.12.0.1/icyllis.modernui.mc.ModernUIClient.loadTypefaceInternal(ModernUIClient.java:389)
	at TRANSFORMER/modernui@3.12.0.1/icyllis.modernui.mc.ModernUIClient.loadTypeface(ModernUIClient.java:344)
	at TRANSFORMER/modernui@3.12.0.1/icyllis.modernui.mc.forge.ConfigImpl$Client.reload(ConfigImpl.java:578)
	at TRANSFORMER/modernui@3.12.0.1/icyllis.modernui.mc.forge.ConfigImpl.reloadAnyClient(ConfigImpl.java:112)
	at TRANSFORMER/modernui@3.12.0.1/icyllis.modernui.mc.forge.ModernUIForge$Client.lambda$new$0(ModernUIForge.java:160)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/javafmllanguage@1.20.1-47.4.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:46)
	at TRANSFORMER/modernfix@5.25.2+mc1.20.1/org.embeddedt.modernfix.forge.config.ConfigFixer$LockingConfigHandler.accept(ConfigFixer.java:53)
	at TRANSFORMER/modernfix@5.25.2+mc1.20.1/org.embeddedt.modernfix.forge.config.ConfigFixer$LockingConfigHandler.accept(ConfigFixer.java:38)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$9(ModContainer.java:172)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:172)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2351)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50)
	at TRANSFORMER/forge@47.4.0/net.minecraftforge.fml.core.ModStateProvider.lambda$new$1(ModStateProvider.java:67)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111)
	at TRANSFORMER/forge@47.4.0/net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:66)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:209)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:209)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.ModLoader.lambda$loadMods$15(ModLoader.java:190)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at LAYER PLUGIN/fmlcore@1.20.1-47.4.0/net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:190)
	at TRANSFORMER/forge@47.4.0/net.minecraftforge.client.loading.ClientModLoader.lambda$startModLoading$5(ClientModLoader.java:94)
	at TRANSFORMER/forge@47.4.0/net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:86)
	at TRANSFORMER/forge@47.4.0/net.minecraftforge.client.loading.ClientModLoader.startModLoading(ClientModLoader.java:94)
	at TRANSFORMER/forge@47.4.0/net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:77)
	at TRANSFORMER/forge@47.4.0/net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:86)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

[073月2026 01:11:01.892] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font 'tetra:ascii_small' in pack: 'mod_resources'
[073月2026 01:11:01.892] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font bundle: 'tetra:font/ascii_small.json', font set: [tetra:ascii_small / minecraft:space,tetra:font/ascii_small.png]
[073月2026 01:11:01.893] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font 'minecraft:default' in pack: 'vanilla'
[073月2026 01:11:01.934] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font 'minecraft:default' in pack: 'file/Reimagined_[v1.45].zip'
[073月2026 01:11:01.934] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font bundle: 'minecraft:font/default.json', font set: [minecraft:include/space,minecraft:include/default,minecraft:lang_symbols/item_description/test_desc2.png]
[073月2026 01:11:01.938] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font 'minecraft:illageralt' in pack: 'vanilla'
[073月2026 01:11:01.938] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font bundle: 'minecraft:font/illageralt.json', font set: [minecraft:include/space,minecraft:font/asciillager.png]
[073月2026 01:11:01.955] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font 'supplementaries:include/antiquable' in pack: 'mod_resources'
[073月2026 01:11:01.955] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font bundle: 'supplementaries:font/include/antiquable.json', font set: [supplementaries:font/antiquable_cyrillic.png,minecraft:font/nonlatin_european.png,supplementaries:font/antiquable_accented.png,supplementaries:font/antiquable.png]
[073月2026 01:11:01.965] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font 'minecraft:include/default' in pack: 'vanilla'
[073月2026 01:11:01.965] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font bundle: 'minecraft:font/include/default.json', font set: [minecraft:font/nonlatin_european.png,minecraft:font/accented.png,minecraft:font/ascii.png]
[073月2026 01:11:01.967] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font 'minecraft:include/space' in pack: 'vanilla'
[073月2026 01:11:01.967] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded raw font bundle: 'minecraft:font/include/space.json', font set: [minecraft:include/space / minecraft:space]
[073月2026 01:11:01.979] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded font: 'minecraft:include/space', font set: [minecraft:include/space / minecraft:space]
[073月2026 01:11:01.981] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded font: 'minecraft:include/default', font set: [minecraft:font/nonlatin_european.png,minecraft:font/accented.png,minecraft:font/ascii.png]
[073月2026 01:11:01.981] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded font: 'minecraft:default', font set: [minecraft:include/space / minecraft:space,minecraft:font/nonlatin_european.png,minecraft:font/accented.png,minecraft:font/ascii.png,minecraft:lang_symbols/item_description/test_desc2.png]
[073月2026 01:11:01.981] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded font: 'minecraft:illageralt', font set: [minecraft:include/space / minecraft:space,minecraft:font/asciillager.png]
[073月2026 01:11:01.981] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded font: 'supplementaries:include/antiquable', font set: [supplementaries:font/antiquable_cyrillic.png,minecraft:font/nonlatin_european.png,supplementaries:font/antiquable_accented.png,supplementaries:font/antiquable.png]
[073月2026 01:11:01.981] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded font: 'supplementaries:antiquable', font set: [minecraft:include/space / minecraft:space,supplementaries:font/antiquable_cyrillic.png,minecraft:font/nonlatin_european.png,supplementaries:font/antiquable_accented.png,supplementaries:font/antiquable.png,SansSerif]
[073月2026 01:11:01.981] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded font: 'tetra:ascii_small', font set: [tetra:ascii_small / minecraft:space,tetra:font/ascii_small.png]
[073月2026 01:11:01.981] [Worker-ResourceReload-5/INFO] [ModernUI-MC/TextLayout]: Loaded font: 'minecraft:alt', font set: [minecraft:include/space / minecraft:space,minecraft:font/ascii_sga.png]
[073月2026 01:11:02.417] [Finalizer/WARN] [ModernFix/]: One or more BufferBuilders have been leaked, ModernFix will attempt to correct this.
[073月2026 01:11:02.484] [Render thread/INFO] [EMI/]: [EMI] Disconnecting from server, EMI data cleared
[073月2026 01:11:02.492] [Thread-15/INFO] [EMI/]: [EMI] Clearing data
[073月2026 01:11:02.510] [Render thread/INFO] [de.keksuccino.fancymenu.customization.layer.ScreenCustomizationLayerHandler/]: [FANCYMENU] ScreenCustomizationLayer registered: generic_dirt_message_screen
[073月2026 01:11:02.671] [Render thread/INFO] [mixin/]: Mixing MixinGuiBook from enigmaticlegacy.mixins.json into vazkii.patchouli.client.book.gui.GuiBook
[073月2026 01:11:02.672] [Render thread/INFO] [mixin/]: Renaming synthetic method lambda$onOpenWebLink$0(Ljava/lang/String;Lnet/minecraft/client/Minecraft;Lnet/minecraft/client/gui/screens/Screen;Z)V to mde01bcc$lambda$onOpenWebLink$0$0 in enigmaticlegacy.mixins.json:MixinGuiBook from mod (unknown)
[073月2026 01:11:03.149] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:961) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.4.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.4.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.4.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:112) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:105) ~[?:?]
Caused by: java.lang.SecurityException: setContextClassLoader
	at java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:231) ~[?:?]
	at org.sinytra.connector.service.hacks.ConnectorForkJoinThreadFactory.newThread(ConnectorForkJoinThreadFactory.java:25) ~[%5B前置%5D%20信雅互联-Connector-1.0.0-beta.46+1.20.1.jar%23390!/:1.0.0-beta.46+1.20.1]
	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1574) ~[?:?]
	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1712) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.push(ForkJoinPool.java:1156) ~[?:?]
	at java.util.concurrent.ForkJoinTask.fork(ForkJoinTask.java:633) ~[?:?]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:307) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.betterx.bclib.client.models.CustomModelBakery.loadCustomModels(CustomModelBakery.java:38) ~[%5B前置-更好的末地%5D%20bclib-3.0.14_mapped_srg_1.20.1.jar%231366!/:?]
	at net.minecraft.client.resources.model.ModelManager.handler$hjh000$bclib$loadCustomModels(ModelManager.java:2530) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5540_(ModelManager.java:78) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10827_(SimpleReloadInstance.java:32) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.<init>(SimpleReloadInstance.java:44) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10815_(SimpleReloadInstance.java:32) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_203834_(SimpleReloadInstance.java:101) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.mixinextras$bridge$m_203834_$18(ReloadableResourceManager.java) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.mde01bcc$moonlight$lambda$moonlight$clientDynamicPackEarlyReload$0$1(ReloadableResourceManager.java:1545) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.mehvahdjukaar.moonlight.core.misc.ReloadInstanceWrapper.lambda$new$1(ReloadInstanceWrapper.java:49) ~[%5B前置%5D%20moonlight-1.20-2.16.19-forge.jar%23506!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	... 19 more
[073月2026 01:11:03.217] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID e218fa72-6e46-4dc4-ae86-09afdc071327
```

</p>
</details>

**Comment by Tigercrl** [comment]
NonUpdate 也用了 SecurityManager 不过新版 JDK 把这个移除了我再看看有什么办法吧（大概率没有）
